### ISSUE TITLE
TetGen uncaught error on some instances

### ISSUE THREAD

**Issue by Turtoise1** [cpmech/tritet#8]
Hey! Thank you for your work on wrapping TetGen in your crate. It really saved me some time for my private project.

By coincidence i discovered that some instances let the program crash without giving the possibility to handle the error.
It might be that these instances are not solvable, i'm not too deep into how the algorithm works, but it would be nice if the program not just crashes but gives the error to me so that i can handle these instances.

Here's an example instance on when the algorithm crashes:
```
let mut tetgen = Tetgen::new(4, None, None, None)?;
tetgen.set_point(0, 0, -1, 0, 0);
tetgen.set_point(1, 0, 0, 0, 0);
tetgen.set_point(2, 0, 1, 0, 0);
tetgen.set_point(3, 0, 0, 1, 0);
tetgen.generate_delaunay(false)?;
```

And here's the error message:
```
c_code/predicates.cxx:636: void exactinit(int, int, int, double, double, double): Assertion `maxz > 0' failed.
```

I think the problem is that the three points in a line and the extra point cannot be put into a tetraeder. But it would be nice if i could catch the error and the program would not crash because in my program the points are created at runtime and such an instance can appear by accident. If it appears i would like to handle it differently.

**Comment by cpmech** [comment]
Hi, thanks for the suggestion!

The `assert` method used by TetGen has now been replaced by a better error-handling in version `1.0.0`.

For example, the following test was added:

```rust
#[test]
fn handle_coplanar_points() -> Result<(), StrError> {
    let mut tetgen = Tetgen::new(4, None, None, None)?;
    tetgen.set_point(0, 0, -1.0, 0.0, 0.0)?; // z=0
    tetgen.set_point(1, 0, 0.0, 0.0, 0.0)?; // z=0
    tetgen.set_point(2, 0, 1.0, 0.0, 0.0)?; // z=0
    tetgen.set_point(3, 0, 0.0, 1.0, 0.0)?; // z=0, thus, all points are coplanar
    assert_eq!(
        tetgen.generate_delaunay(false).err(),
        Some("TetGen failed: points are probably coplanar")
    );
    Ok(())
}
```

Cheers and Happy New Year.

**Comment by Turtoise1** [comment]
Thanks for the quick adjustment, worked perfectly for my cases.
Happy new year!
